# Generated by Django 2.0.13 on 2019-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='logo.png', upload_to=''),
        ),
    ]
